### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by coherenceNFT** [Turk-Mumtaz/nft-sales-bot#1]
Hello! thanks for your bot
i'm trying to test this, but keep getting this error:

Sale at 19/10/2021 00:52:48 ---> 0.00145768 SOL
Signature:  5zoFddzUYbhGgJ8p8dWtPkCA4j51DyCxQDHgF9rNYa31oovJFnkdvp7LcEU7Nstx8wbMDavaRBdTuG3osvykgXWp
Name:  Biochip 90
Image:  https://www.arweave.net/oX4gDexzvuvS7ZtosxkvL2HKgEb5YnmjNFRI04cKmp4?ext=jpg
Marketplace:  Magic Eden
error while going through signatures:  TypeError: Cannot read property 'name' of undefined
    at runSalesBot (/home/crohr/repos/solana_bots_ventas/nft-sales-bot/sales_bot.js:62:59)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
-------------------------------------------
Sale at 19/10/2021 00:53:08 ---> 2.400005 SOL
Signature:  vRjZk9y43eCA3kNjSCtCk66tF5DgrZgiKwSJvQVYpzufPwJGA1WS9pXvSDTPb9TyAwWXYr1bTqBVJay6Vsi4493
Name:  Biochip 20
Image:  https://www.arweave.net/ReHoeEljVWILmPkCRffrx4KWf4tdZcH65vxp0Eysxc8?ext=png
Marketplace:  Magic Eden
error while going through signatures:  TypeError: Cannot read property 'name' of undefined
    at runSalesBot (/home/crohr/repos/solana_bots_ventas/nft-sales-bot/sales_bot.js:62:59)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
-------------------------------------------
Sale at 19/10/2021 00:55:56 ---> 0.00145768 SOL
Signature:  3TMekK4FFTkM27PqmdecKSnJz5J7LsjEU7ND3oU53vt3v6tgcK39YAEA8UcBJ6GiiuuJHaqxz2chFADVah3LoqhN
Name:  Fluidal 10
Image:  https://www.arweave.net/UrheObpaTYGkefK82j3-Tj53VgqLNjg8aFvrvDEtUE4?ext=png
Marketplace:  Magic Eden
error while going through signatures:  TypeError: Cannot read property 'name' of undefined
    at runSalesBot (/home/crohr/repos/solana_bots_ventas/nft-sales-bot/sales_bot.js:62:59)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by Turk-Mumtaz** [comment]
should be fixed now!
